### PR TITLE
Add Table component

### PR DESCRIPTION
**Pull request by palewire**
[Screencast from 2023-03-27 14-45-14.webm](https://user-images.githubusercontent.com/9993/228037321-95aa0af8-0b36-4fcf-ad1f-dbacbe4d2d36.webm)

### What's in this pull request

- [ ] Bug fix
- [x] New component/feature
- [ ] Documentation update
- [ ] Other

### Description

This patch aims to add a new component, `Table`, that offers a straightforward way to publish tabular data. Among other things, it includes options to allow users to search, filter and sort. @hobbes7878, I'm sure there are many a bone to pick here. Please let me know how I can improve this offering.

### Before submitting, please check that you've

- [x] Read our [contributing guide](https://github.com/reuters-graphics/graphics-components/blob/master/CONTRIBUTING.md) at some point
- [x] Formatted you code correctly (i.e., prettier cleaned it up)
- [x] Documented any new components or features
- [x] Tagged an editor to review

### CODE REVIEW

**Comment by hobbes7878** [comment]
This looks great, Ben. Many thanks for including the typings, as well.

After a first look, there are a few small things I'd like to check it for and then I think we can pull this in:
- [ ] Check for theme compatibility. Few things in the styles using SCSS variables that I think we want to use available CSS variables (so clients can control the styles, as well).
- [ ] Have @pkd2512 take a look at the typography. (Prasanta is currently working on a big update to our type design system,  so some of this may happen in a point update _after_ that lands, but worth him vetting it at this point.)
- [ ] _General_ style review with @pkd2512, too.
- [ ] See if a few of the props that take rich markup could use a corresponding slot, instead. So for example, on the [Headline component](https://reuters-graphics.github.io/graphics-components/?path=/docs/components-headline--default) you'll see both a `hed` prop and a hed [slot](https://svelte.dev/tutorial/named-slots), which takes precedence over the prop when it's provided and is a handy escape hatch to let folks punch in more complex markup.

... Anyway all most minor things I think P and I can pitch back to you in a PR to your branch, if that works. But let me know if you're on a crunch to get this in so you can use it, too.

**Comment by pkd2512** [comment]
Hello Ben,

I took a quick look at the demo and it works great! @hobbes7878 has already mentioned some of the `Theme` stuff, which needs to be wired in eventually. Outlining some other thoughts – 

* The search and filter elements can be minimal and expanded on demand. 
* The pagination can be reduced to media-player-like action buttons perhaps. 
* Some layout shift happens when the size of the text in columns change. Maybe can add some smart logic to minimise that.
* Need to account for text styles and overflow on small screens.
* Accessibility of the table content for screen readers. (cc. @AditiBhandariTR @MinamiFunakoshiTR)

Since we don't have many buttons/text boxes in our components, this may be a good time to iterate on some designs that can be made as our default. This probably needs a trip to Figma to see some layout and visual design options, which we can incorporate into the component styles. 


💡 Also, as an enhancement, what if we had the ability to plug in a `DOM element`/`svelte component` as the content of the table cell instead of just text? Something like -

image


[Some inspiration from DataWrapper](https://academy.datawrapper.de/article/247-examples-of-datawrapper-tables)

**Comment by hobbes7878** [comment]
Marking as draft PR until we get accessibility, mobile styles and theme compatibility checked off.

**Comment by palewire** [comment]
Thanks for the detailed feedback. If you guys know the changes you want, I'm happy to let you make them in the branch. But I don't want to give you homework either. If you'd like me to take another lap based on your instructions just say the word.

A couple specifics related to what you listed:
* I'm not attached to the current pagination style. For your information, I mostly lifted it from the search results page on reuters.com. I'm fine with departing from that approach, but I figure it's worth mentioning that's where it comes from.

* I suspect that how to handle mobile device widths is the trickest question for any table design these days. I'm of the view that a simple x-overflow scroll is the easiest solution (as opposed to flopped vertical boxes) as the default. I'd argue the simplicity the x scroll offers is hard to top. But maybe it's just all the time I spend on baseball-reference.com. I could imagine designing an option that allowed the developer to pick between those two common approaches. Or maybe there's a third approach you like even better. Let me know what you think.

**Comment by hobbes7878** [comment]
If you're not in too big a hurry to see this out in the world, Ben, then I'd actually like if we can take a beat with it, our side. It's a solid component idea, and you've done the heavy lifting on the functionality. A couple things we'll solve more quickly w/r/t `Theme` vars, and it's a good design exercise around the edges for Prasanta so I'd like to let him take a quick whack at it in design mock. (P, we don't need to solve buttons for all time right now, tho... Let's let that aggregate up from a couple more components and try to short track this one.)

**Comment by palewire** [comment]
No hurry here. Let's pour the concrete and set a solid foundation. Let me know how I can help.

**Comment by pkd2512** [comment]
This sounds good. As soon as I get some time, I will mock something up here.

https://www.figma.com/file/WCGRlfhqmQQKwGzBSLeann/Table-component?node-id=0%3A1&t=QO24wDMmxCCz9q3t-1

**Comment by palewire** [comment]
That's great. I think it all looks doable. I can take a pass when I have a little time. The only new feature I think it would require is that truncated approach, which I don't think will be tough to add. The only question I have there is what we'd prefer as the default behavior. Should it paginate by default? Truncate by default? Neither?

**Comment by hobbes7878** [comment]
Personal pref, but I think I'd paginate by default. Fwiw, I don't see us using the truncated option much. Can wire that in later if we find that's not the case.

Ben, if you want to go splitzies on dev, I'm keen to set up optionally passing components as cell values so we can do sparklines and such and while we're at it some custom styling accessors for columns so we can have heat tables, too. I won't get to it for a bit, but happy to pile on some actual time when I can.

**Comment by palewire** [comment]
Okay @hobbes7878 and @pkd2512. I've taken a pass through the code and consulted your designed. Here's what you should find changed:

- A ton of style tweaks to try to bring it into line with your ideas
- A new truncated feature
- Most of the smaller subcomponents broken out into separate Svelte files
- A bunch of documentation fixes

Things I'm not sure about:

- I don't think I really nailed your idea for the pagination feature. Let me know what you think and how it could improve.
- I couldn't think of a good way to implement the gradient fade on x-overflow. What conditional would that peg on? I'm probably just being a blockhead about it.

Let me know what you think. Any and all critique welcome. I'm sure I screwed something else up.

**Comment by hobbes7878** [comment]
@pkd2512 This looks good to me with the colour and font variables incorporated. May be some font weighting stuff you want to polish, but I'd say let's add that to the major point release coming with yer new type system.

One thing I don't think I understood rightly first time around is the bars between pagination buttons. Ben's interpreted those as a loading indicator, so like one bar is 33% through all pages, 2 is 66%, etc. I took it as a bar _per page_, but, of course, we could have quite long tables with many pages...

Why don't we just ditch the bars and centre-align the numbers; they don't bring much to the party for me, anyway:
image

**Comment by pkd2512** [comment]
> @pkd2512 This looks good to me with the colour and font variables incorporated. May be some font weighting stuff you want to polish, but I'd say let's add that to the major point release coming with yer new type system.
> 
> One thing I don't think I understood rightly first time around is the bars between pagination buttons. Ben's interpreted those as a loading indicator, so like one bar is 33% through all pages, 2 is 66%, etc. I took it as a bar _per page_, but, of course, we could have quite long tables with many pages... image
> 
> Why don't we just ditch the bars and centre-align the numbers; they don't bring much to the party for me, anyway: image

Will take a closer look, but the style looks fine and we can add minor tweaks with the DS release later.

Re: Pagination, the idea for the bars is the same as what we would have on a photo carousel.
They add a custom way to navigate the table pages, besides the linear flow that is provided by the arrows. So, the bars actually _indicate the number of pages_ as well as _on:click navigate to that page_ of the table. 
In a scenario, where there are lots of pages (which is when you don't truncate, but paginate), this can be a value add perhaps.

**Comment by pkd2512** [comment]
For the sorting:
1. The icon (greyed) should be present on all the columns that can be sorted upon. There can be a prop to choose sortable columns. This is because we don't want sort columns like "Notes" that is not much useful.
2. The arrow on active sorting should be the darker colour to indicate the current sort status.

There seems to be a bug with the sort icon. On clicking the icon, it disappears.

Also, an issue with sorting paginated data is that there is quite a layout shift when longer names show up. Maybe, give equal widths/some fixed width to columns (default) and let the widths be configurable using CSS or props. So, if the columns have `id` based on the slug of the header, one could use target them in CSS to assign % widths.

For non-paginated tables, I guess auto-layout works just fine. It would still be nice to be able to control the widths across viewport sizes, especially for cases where there is a dataviz or something in the cells.

**Comment by pkd2512** [comment]
### Customising columns

image

Making the columns targetable using CSS will also enable customising things like alignment within columns etc. We may not always want numeric fields to be right-aligned, especially if they are in the middle of the table.

**Comment by pkd2512** [comment]
**Re: faded overlay on wider mobile tables**

1. Maybe we add an overlay gradient on the table (with `pointer-events:none`). This can also have some animated icon indicator to show that it is scrollable. 
2. Detect to see if it has been scrolled horizontally and then hide the overlay. We only need to show the feature once to a reader.

I kinda used a logic similar to this for our [COVID tracker](https://www.reuters.com/graphics/world-coronavirus-tracker-and-maps/vaccination-rollout-and-access/). 


scroll

**Comment by pkd2512** [comment]
### Sticky table headers

It will be nice to have the table header be sticky by default. For tables smaller than window height, it will not do anything. But when it overflows, it will be a nice thing.

P.S. This is irrespective of whether it's a regular, truncated or paginated table.

scroll


https://www.figma.com/proto/WCGRlfhqmQQKwGzBSLeann/Table-component?page-id=0%3A1&node-id=8-328&viewport=349%2C274%2C0.08&scaling=scale-down&starting-point-node-id=8%3A503&show-proto-sidebar=1

**Comment by palewire** [comment]
> Re: Pagination, the idea for the bars is the same as what we would have on a photo carousel. They add a custom way to navigate the table pages, besides the linear flow that is provided by the arrows. So, the bars actually _indicate the number of pages_ as well as _on:click navigate to that page_ of the table. In a scenario, where there are lots of pages (which is when you don't truncate, but paginate), this can be a value add perhaps.

So how would you handle a case where there are many pages, like say 25 or 50 pages?

**Comment by palewire** [comment]
> For the sorting ...

Thanks for scrubbing this feature. I flipped the arrow colors. They now appear in all cases. You get two gray ones when the column isn't responsible for the sort. I added a `sortableFields` options to let you limit which ones can sort. 

[Screencast from 2023-04-05 15-25-21.webm](https://user-images.githubusercontent.com/9993/230184358-2052a446-6464-4dfd-a56c-1a06977eba82.webm)

**Comment by palewire** [comment]
> Customizing columns ....

Columns are tagged with a `data-field` attribute. I've added a section to the docs showing how you'd target them with CSS. I've also removed the auto-alignment feature. In retrospect, its pants were too fancy.

image

**Comment by palewire** [comment]
> Sticky table headers ...

I've set `position: sticky` on the `<th>` elements, but they don't seem to be sticking. Am I missing something obvious here? The online posts I can find all say it should. And so does ChatGPT! ;) So I must be missing something obvious here. Is there some conflicting CSS on the table? I can keep banging on it but if you know the answer please fill me in.

**Comment by palewire** [comment]
> **Re: faded overlay on wider mobile tables**

Can you point me directly to an example you'd like to replicate? Despite being a bit dull, I'm running low on protein and not seeing it on the page you linked.

**Comment by pkd2512** [comment]
> > **Re: faded overlay on wider mobile tables**
> 
> Can you point me directly to an example you'd like to replicate? Despite being a bit dull, I'm running low on protein and not seeing it on the page you linked.

Hey, my bad, that example isn't exactly the faded thing. I just cite that to show similar behaviour with the scroll arrow on the bottom right, which goes away after you scroll. I don't have a direct example of the faded thing.

**Comment by pkd2512** [comment]
> > Re: Pagination, the idea for the bars is the same as what we would have on a photo carousel. They add a custom way to navigate the table pages, besides the linear flow that is provided by the arrows. So, the bars actually _indicate the number of pages_ as well as _on:click navigate to that page_ of the table. In a scenario, where there are lots of pages (which is when you don't truncate, but paginate), this can be a value add perhaps.
> 
> So how would you handle a case where there are many pages, like say 25 or 50 pages?

Hmm, that's a tricky situation. Although, I would imagine still having the bars (auto-sized small) because of an assumption that we would have a balance of table length and the number of pages, so such long tables would be more of an edge case. Maybe for such long tables, you would break it down by some parameter into multiple tables? Or do some custom styling and hide the bars if they don't work. Maybe I am wrong haha. Sending back to @hobbes7878 for suggestions.

**Comment by pkd2512** [comment]
> 

Took a look and seems like the issue is the `overflow-x: hidden` on `section.table`. Position sticky won't work with overflow property set on the parent. Setting that overflow to `unset` made the sticky work for me in the chrome inspector.

**Comment by pkd2512** [comment]
> > Sticky table headers ...
> 
> I've set `position: sticky` on the `<th>` elements, but they don't seem to be sticking. The online posts I can find all say it should. And so does ChatGPT! ;) So I must be missing something obvious here. Is there some conflicting CSS on the table? I can keep banging on it but if you know the answer please fill me in.


Took a look and seems like the issue is the `overflow-x: hidden` on `section.table`. Position sticky won't work with overflow property set on the parent. Setting that overflow to `unset` made the sticky work for me in the chrome inspector.

**Comment by hobbes7878** [comment]
Catching up, but I see 3 things outstanding to get this in:
- **Pagination bars** I've made a call w/ P to drop 'em and can get that into a PR today.
- **Fuzzy right edge on mobile** We can live without for first publish. I have questions about it, anyway.
- **Sticky headers** I can take a pass at this, but if I can't manage, can publish without.

**Comment by palewire** [comment]
Thanks for the help and feedback. Anything else on your minds? The main thing I'm thinking about is whether we're all happy with the mobile layout when things get crammed in.

**Comment by hobbes7878** [comment]
Yeah, mobile is all that's left on my mind.

Our ideal is the table scrolls on X, right? 

_I think_ we have two issues: 1) That CSS0-driven sticky header will not work if any parent has the overflow, which I think we inevitably need to scroll the table. 2) Because the header, dek and controls are all descendents of the table in `<caption>` I don't see how we can width-limit them separately. So, I think we end up with something like: 

image


Ideally, title, dek and controls are all still within the normal text well.

Tables are hard...

**Comment by palewire** [comment]
Hmm. Thanks for catching that. It must be why I had the overflow: hidden in there. My lazy brain's first thought, what if we didn't put all that frontmatter in the `<caption>`? While it has semantic appeal, I suppose it isn't necessary. Could we solve this issue by raising that bit up into a `<div>` above the `<table>` tag?

**Comment by hobbes7878** [comment]
Think we'd have to, yeah. Probably some way to aria-tag it semantically anyway. That solves the bigger problem.

I don't have a solution for the sticky hed, yet. Can google a bit more...

**Comment by palewire** [comment]
Mucked around a bit more with the sticky bit. Couldn't crack it when I started from the bottom up. Is there an example in the real world we could look at for pointers and a top down approach?

**Comment by hobbes7878** [comment]
I'm struggling to find any that don't have hard-coded dimensions, e.g.,  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#displaying_large_tables_in_small_spaces

**Comment by palewire** [comment]
Thanks all for your help on this.

**Pull request merged**
